### ISSUE TITLE
Perma textscreens are truly permanent.

### ISSUE THREAD

**Issue by djsime1** [Cherry/3D2D-TextScreens#22]
_Dear developer, How the f*ck are perma textscreens still spawning even after I delete the sammyserver_textscreens.txt file in the data directory? This is a really big problem and really, REALLY annoying. Please tell me how to fix this witchcraft. ~djsime1_

**Edit: Re-installed addon + deleted data file, textscreens are still there. WTF?**

**Edit 2: I even edited the core lua file so it couldnt read/write data file, textscreens are still there. How?**

**Comment by Cherry** [comment]
Hey djsime1. That's a very... interesting issue.

I don't see how it's possible for the textscreens to still spawn after the file has been deleted. All of the code applicable to loading textscreens data occurs at https://github.com/Cherry/3D2D-TextScreens/blob/master/lua/autorun/textscreens_util.lua#L48-L78. And if you've edited the lua to not even read/write data, then it really can't be this addon causing issues.

Do you have any other addons running that perhaps offer any kind of save states, or saving permanent entities/props, etc? What happens if you disable all other addons entirely - does the issue still occur then?

**Comment by Tomboeg** [comment]
Welp! Sorry for my late reply.

Having the exact same error here.
Just today again I pressed 'remove permatextscreen' and as a result the textscreen did not disappear, but the confirmation that the textscreen was no longer permanent did appear. If i remove it again using the normal 'remove' button it disappears but returns after restart.

The textscreens that appear do not appear in the sammyservers file and there is basically no trace of the textscreens which still appear! This is a high priority issue because I currently have to block off multiple broken textscreens that I cannot remove.

**Comment by Cherry** [comment]
@Tomboeg Can you please try removing all other addons on your server, and running something like sandbox? I'm suspecting a conflict with another addon.

**Comment by Tomboeg** [comment]
Woah! That's a fast reply! Awesome!

I can't really change to sandbox because my server simply can't change to that right now because it's crowded and busy.

I do can give you the list of my addons the server uses.

http://steamcommunity.com/sharedfiles/filedetails/?id=777489368

**Comment by Tomboeg** [comment]
UPDATE.

I might have the solution.
It might be the permaprop tool causing them to become permanent, thus conflicting. I was able to remove a textscreen using the permaprop tool. I can't restart the server just yet but I will update with news once I know more!

**Comment by Cherry** [comment]
Thanks for the list. Could you possible clone your server and run a second one with sandbox, and no other addons so to test if there's any conflict? The more variables you can eliminate the better, as I'm unfortunately completely unable to replicate this in my test environments for both sandbox and DarkRP, with no other addons running.

The permaprop tool is definitely a likely conflict if you're using its saving feature. I imagine this is a similar problem to OP, as I mentioned in my first reply.

**Comment by Tomboeg** [comment]
You erased sammyservers_textscreen with a model of models/hunter/plates/plate1x1.mdl from the database.

**Comment by Tomboeg** [comment]
UPDATE

Great news!
The permaprop tool is the key!
You can delete the 'bugged' textscreens using the permaprop tool.
It seems to be conflicting with that.

My problem has been fixed!

**Comment by Cherry** [comment]
Awesome, thanks very much @Tomboeg! Feel free to create another issue if you run into any other problems.
