### ISSUE TITLE
Textscreens Breaking Server

### ISSUE THREAD

**Issue by Hexical1** [Cherry/3D2D-TextScreens#23]
Hello!

So I have a very very weird bug. For some odd reason, my server crashes at spawning textscreens. It's not a normal crash either, the console stays up, but it freezes. The server is active until I try to connect, at which, once it hits "Spawning Textscreens" it just freezes, and after a short while I get kicked out with no error message. My console doesn't update after this, and gives me 0 errors or logs as to what is causing this. All I know is it happens after "Spawning Textscreens"

I've tried these things:

1. Uncommenting Textscreens in my workshopDL 
2. Deleting Sammy_Textscreens.txt under the /data folder
3. Re-Installing my server and just dropping my garrysmod directory into that
4. A combination of 1 & 2

Thank you for your time, hope we can solve this!

Heres a picture of my console!
![qxr1wle](https://cloud.githubusercontent.com/assets/12714080/20446533/1a0f5cbe-ada8-11e6-90e7-18a920985b36.png)

**Comment by Cherry** [comment]
Thanks for detailed report!

The code in question for spawning textscreens can be found at https://github.com/Cherry/3D2D-TextScreens/blob/master/lua/autorun/textscreens_util.lua#L48-L78. My only thought as to why this could be occurring, is if your "sammyservers_textscreens" is extremely large, but you mentioned that you tried deleting this file and the issue still occurred? 

What happens if you disable every other addon on the server, other than textscreens? There could possibly be a conflict with another addon you have installed. If that works, can you try adding each of your other addons back one by one, until we can find the specific addon causing a conflict?

**Comment by Hexical1** [comment]
Sure can! Will try in a few minutes and update you, thanks for the speedy reply!

**Comment by Hexical1** [comment]
admin-popup screen seems to be the problem.

https://scriptfodder.com/scripts/view/1673

Everything works fine without it, thanks for helping me with my problem!

**Comment by Cherry** [comment]
Thanks very much! Feel free to re-open this issue, or create another if you need anything else.
