### ISSUE TITLE
textscreens doesn't save into the map.

### ISSUE THREAD

**Issue by KochiXD** [Cherry/3D2D-TextScreens#3]
So im running a DarkRP server and everytime we are trying to save the textscreens into the map. it doesn't doo any effect. 
i tried to reinstall the addon few times and to remove the data files, but nothing is changing. do you know why we have that kind of problem ? 
thank you for your help..

**Comment by Dellkan** [comment]
See https://github.com/Cherry/3D2D-TextScreens/issues/1

More than likely caused by another addon in the relevant hook either erroring out, or returning something that it's not supposed to.

Relevant hook is named "InitPostEntity". You can get a list of addons using this hook by calling `lua_run for k, v in pairs(hooks.GetTable()["InitPostEntity"]) do print(k, debug.getinfo( v ).short_src) end` in rcon console. One of lines in the subsequent output will be responsible.

**Comment by Cherry** [comment]
Feel free to re-open this issue in the future with any further information.
