### ISSUE TITLE
Gmod update today broke your addon

### ISSUE THREAD

**Issue by xXthatNAVYguyXx** [Cherry/3D2D-TextScreens#4]
As you may or may not know, Garry released a new update today (you can read more about it here ------> http://www.garrysmod.com/2015/03/09/15-03-09/ ). This update has broken many addons. Most are the problems are hud and gui based as Garry has made changes to these systems. As for right now 3D2D Text Screens don't even show up in my tool menu which makes me think this addon was disabled due to errors. It worked fine before the update. I would like to be able to use this addon for my server in the future but as for right now I cannot.

**Comment by Cherry** [comment]
I'm not able to replicate this on a clean install, both single player and on a server.

What's likely happening is another one of your addons causing an error someone that's preventing further addons from loading. I'd recommend disabling any other erroring addons.

There also hasn't been any other reports of this issue since the update release, which would generally happen very quickly if there were widespread issue. If you have any more information, or continue to have the issue on a clean install, with only this addon, I'd be happy to take another look.
