### ISSUE TITLE
Chromium update error with textscreens

### ISSUE THREAD

**Issue by Jango2225** [Cherry/3D2D-Textscreens#44]
[ERROR] addons/3d2d_aurebesh_textscreens_1191355200/lua/entities/sammyservers_textscreen/cl_init.lua:109: bad argument #1 to 'GetTextSize' (string expected, got nil)
  1. GetTextSize - [C]:-1
   2. AddDrawingInfo - addons/3d2d_aurebesh_textscreens_1191355200/lua/entities/sammyservers_textscreen/cl_init.lua:109
    3. func - addons/3d2d_aurebesh_textscreens_1191355200/lua/entities/sammyservers_textscreen/cl_init.lua:134
     4. unknown - lua/includes/extensions/net.lua:32

this is what I get when I load in.. please fix it or tell me how to fix it.. thanks!

**Comment by Cherry** [comment]
It looks like you're using a modified version of the addon, specifically `3d2d_aurebesh_textscreens_1191355200`, from https://steamcommunity.com/sharedfiles/filedetails/?id=1191355200. The stack trace there and line numbers do not match the current code-base: https://github.com/Cherry/3D2D-Textscreens/blob/master/lua/entities/sammyservers_textscreen/cl_init.lua.

They haven't pushed an update since 2017, so the code-base they're using is very out of date. You'll need to contact the author of this modification for assistance, or try using the official version at https://steamcommunity.com/sharedfiles/filedetails/?id=109643223.
