### ISSUE TITLE
Textscreen can be made into a fading door.

### ISSUE THREAD

**Issue by Nguyen-Gmod** [Cherry/3D2D-Textscreens#60]
Hey Cherry, this has been a low-key exploit for a while but a big youtuber just leaked it so I reckon now would be a good time to report it.

Basically text screens can be turned into fading doors using the fading door tool, once faded, they can't be removed by admins via physgun or remover tool unless they're unfaded. Dont know if there is anything you can do to prevent this on the text screen side.

Anyways, deuces ✌

**Comment by Cherry** [comment]
Thanks for the report. I assume the addon in question is this one? https://steamcommunity.com/sharedfiles/filedetails/?id=115753588

I already implement a `CanTool` hook to prevent other tools from causing problems with Textscreens as per https://github.com/Cherry/3D2D-Textscreens/blob/9ec0953f3811fb4958815b0604b1bb5ffeb80c94/lua/entities/sammyservers_textscreen/init.lua#L48, but it appears that the Fading Door tool doesn't respect this.

I don't think there's going to be anything I can do on my end to "fix" this unfortunately, and seeing as the Fading Door tool hasn't received an update since 2015 (at least not on the Workshop), I don't foresee this being fixed on their end either.

I'll take a closer look at this when I can to see if there's any "hacks" I can implement to work-around this, but this may just be a case of an incompatible addon unfortunately.

**Comment by Nguyen-Gmod** [comment]
Maybe you could possibly do something with textscreen entities "Think" function? https://github.com/Lexicality/fadingdoors/blob/master/lua/includes/modules/fadingdoors.lua. it seems that when something is made a fading door it is given the .isFadingDoor property. Maybe in the think hook you can check if .isFadingDoor == nil and if it isn't set ._fade.active = false on itself. Not sure if this would work though, just gave the fading door code a once over. Thanks for the quick reply!

**Comment by Cherry** [comment]
That's possible to implement race-conditions I'd imagine, and I'm not really wanting to run code in this addon on _every frame_ to fix another addon. 

I'll see if there's another solution.

**Comment by Cherry** [comment]
I've actually been completely unable to replicate this. `CanTool` is calling exactly as I would expect, and the Fading Door tool is being blocked.

I've tested in Single Player, Local Server, and on a dedicated server, all running Sandbox, with [Fading door tool](https://steamcommunity.com/sharedfiles/filedetails/?id=115753588) and [3D2D Textscreens](https://steamcommunity.com/sharedfiles/filedetails/?id=109643223), and I'm unable to use the Fading Door tool on Textscreens, as expected.

Here's a brief video detailing what I'm describing: https://up.jross.me/8bjec
(I'm spam clicking on the fading door to try and get it to click, but it simply will not, and I see my `CanTool` hook being fired as appropriate)

I'm going to need more information to debug this further.

- Is it possible this issue is occurring in a specific gamemode?
- Or on a specific server?
- Or with another addon installed?
- Can you replicate and then provide me steps to replicate the issue locally?

It smells like something like overriding `CanTool` to me.

**Comment by cdymlr** [comment]
wouldn't
`if IsValid(ent) and ent:GetClass() == "sammyservers_textscreen" then return false end
`
to fading door tool be a fix?

**Comment by Cherry** [comment]
Sure, but hardcoding those kind of things in any tool isn’t ideal, and the fading door tool isn’t likely to receive an update. That’s what `CanTool` is for though. Everything I and Fading Doors are doing works fine with each other, and I already prevent other tools from messing with textscreens.

Something on particular servers, be it a gamemode, other addon, etc. is causing this bug. My guess would be something overriding `CanTool`. Any affected servers will need to investigate this themselves, and find which addon, gamemode, config, etc. they have that is causing this.

Until these servers find the underlying issue with their setups, more bugs and incompatibilities are likely to be found with other tools.

**Comment by cdymlr** [comment]
Most servers affected are likely running an outdated version of your addon. 
Can confirm this is not an issue running the latest workshop version. 
Thanks for your hard work!

**Comment by OwjoTheGreat** [comment]
Possibly a stupid suggestion but could it be FPP (DarkRP's default tool/prop protection) that is causing the issue of allowing the entity to be targeted? I know there are a few places where it does some edgy overriding and forces itself into priority. Just throwing a suggestion.

**Comment by Cherry** [comment]
> Possibly a stupid suggestion but could it be FPP (DarkRP's default tool/prop protection) that is causing the issue of allowing the entity to be targeted? I know there are a few places where it does some edgy overriding and forces itself into priority. Just throwing a suggestion.

It's definitely possible. I've had a few people report to me that it doesn't happen on all DarkRP servers though, or on all servers with FPP - only select ones. Perhaps a poorly or default configured FPP?

**Comment by 0xym0ron** [comment]
bump, this is still an issue and needs to be addressed as the youtuber continues to upload videos of him exploiting this bug, children are beginning to learn how to do it 
I tried to contact various fading door tool steam workshop creators but they're all inactive accounts, the only chance is for 3d2d textscreens to release an update via their workshop and stop this once and for all. 
i'd be willing to fix the issue myself if you don't have the time to

**Comment by IGEclipse** [comment]
@0xym0ron like Cherry said, it only works on specific DarkRP based servers. I've attempted to replicate the bug but I have been unable to. The textscreen addon already has anti-abuse for tools.

**Comment by Cherry** [comment]
@0xym0ron Exactly as others have said, yep. I already do everything I can in Textscreens to prevent abuse from other tools via a `CanTool` hook - spin up a Sandbox game with just Textscreens and Fading Doors installed and you'll find you're completely unable to use Fading Doors on Textscreens, as intended.

This bug is specific to something on these servers, be it a configuration, gamemode, other addon, etc. likely overriding `CanTool`, allowing Fading Doors to be used on Textscreens. These affected servers will need to diagnose this on their end.

**Comment by D34THC47** [comment]
fixed it guys

to fix the issue with perm text you can't touch go here: **addons/permaprops/lua/permaprops/sv_permissions.lua**

comment out these 2 lines:

```
timer.Simple(5, function() hook.Remove("CanTool", "textScreensPreventTools") end) -- ♥♥♥♥ OFF
timer.Simple(5, function() hook.Remove("CanTool", "textscreenpreventtools") end)
```
so they look like this

```

--timer.Simple(5, function() hook.Remove("CanTool", "textScreensPreventTools") end) -- no you ♥♥♥♥ OFF
--timer.Simple(5, function() hook.Remove("CanTool", "textscreenpreventtools") end) 
```

**Comment by Cherry** [comment]
Oh wow, so PermaProps is removing my hooks, causing these issues? I've opened an issue over on their GitHub to track this: https://github.com/MalboroDEV/PermaProps/issues/22

**Comment by Nguyen-Gmod** [comment]
🤔 interesting that permaprops would even add this considering ss texscreen has a perma feature.

**Comment by D34THC47** [comment]
well least we can all stop this shit happening to our servers now ;)

**Comment by Cherry** [comment]
I've renamed the hooks in this tool as per https://github.com/Cherry/3D2D-Textscreens/commit/64447799b515476cdc7a6007c0d8eb117a1ccbbe as a very quick work-around to avoid PermaProps from removing them. Servers should update ASAP to avoid the problem, until PermaProps removes their hook removal code as per https://github.com/MalboroDEV/PermaProps/issues/22

**Comment by Cherry** [comment]
Thanks to all who reported the issue. https://github.com/MalboroDEV/PermaProps/issues/22 was resolved as per https://github.com/MalboroDEV/PermaProps/commit/4960262c7223335ba295644f189fea452d67dce9, so I'm going to go ahead and close this now.
